--
-- Table structure for table 'district'
--

CREATE TABLE IF NOT EXISTS district (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  region varchar(100) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

INSERT INTO district (id, name, region) VALUES
(1, 'Buikwe', 'central'),
(2, 'Bukomansimbi', 'central'),
(3, 'Butambala', 'central'),
(4, 'Buvuma', 'central'),
(5, 'Gomba', 'central'),
(6, 'Kalangala', 'central'),
(7, 'Kalungu', 'central'),
(8, 'Kampala', 'central'),
(9, 'Kayunga', 'central'),
(10, 'Kiboga', 'central'),
(11, 'Kyankwanzi', 'central'),
(12, 'Luweero', 'central'),
(13, 'Lwengo', 'central'),
(14, 'Lyantonde', 'central'),
(15, 'Masaka', 'central'),
(16, 'Mityana', 'central'),
(17, 'Mpigi', 'central'),
(18, 'Mubende', 'central'),
(19, 'Mukono', 'central'),
(20, 'Nakaseke', 'central'),
(21, 'Nakasongola', 'central'),
(22, 'Rakai', 'central'),
(23, 'Sembabule', 'central'),
(24, 'Wakiso', 'central'),
(25, 'Amuria', 'eastern'),
(26, 'Budaka', 'eastern'),
(27, 'Bududa', 'eastern'),
(28, 'Bugiri', 'eastern'),
(29, 'Bukedea', 'eastern'),
(30, 'Bukwo', 'eastern'),
(31, 'Bulambuli', 'eastern'),
(32, 'Busia', 'eastern'),
(33, 'Butaleja', 'eastern'),
(34, 'Buyende', 'eastern'),
(35, 'Iganga', 'eastern'),
(36, 'Jinja', 'eastern'),
(37, 'Kaberamaido', 'eastern'),
(38, 'Kaliro', 'eastern'),
(39, 'Kamuli', 'eastern'),
(40, 'Kapchorwa', 'eastern'),
(41, 'Katakwi', 'eastern'),
(42, 'Kibuku', 'eastern'),
(43, 'Kumi', 'eastern'),
(44, 'Kween', 'eastern'),
(45, 'Luuka', 'eastern'),
(46, 'Manafwa', 'eastern'),
(47, 'Mayuge', 'eastern'),
(48, 'Mbale', 'eastern'),
(49, 'Namayingo', 'eastern'),
(50, 'Namutumba', 'eastern'),
(51, 'Ngora', 'eastern'),
(52, 'Pallisa', 'eastern'),
(53, 'Serere', 'eastern'),
(54, 'Sironko', 'eastern'),
(55, 'Soroti', 'eastern'),
(56, 'Tororo', 'eastern'),
(57, 'Abim', 'northern'),
(58, 'Adjumani', 'northern'),
(59, 'Agago', 'northern'),
(60, 'Alebtong', 'northern'),
(61, 'Amolatar', 'northern'),
(62, 'Amudat', 'northern'),
(63, 'Amuru', 'northern'),
(64, 'Apac', 'northern'),
(65, 'Arua', 'northern'),
(66, 'Dokolo', 'northern'),
(67, 'Gulu', 'northern'),
(68, 'Kaabong', 'northern'),
(69, 'Kitgum', 'northern'),
(70, 'Koboko', 'northern'),
(71, 'Kole', 'northern'),
(72, 'Kotido', 'northern'),
(73, 'Lamwo', 'northern'),
(74, 'Lira', 'northern'),
(75, 'Maracha-Terego', 'northern'),
(76, 'Moroto', 'northern'),
(77, 'Moyo', 'northern'),
(78, 'Nakapiripirit', 'northern'),
(79, 'Napak', 'northern'),
(80, 'Nebbi', 'northern'),
(81, 'Nwoya', 'northern'),
(82, 'Otuke', 'northern'),
(83, 'Oyam', 'northern'),
(84, 'Pader', 'northern'),
(85, 'Yumbe', 'northern'),
(86, 'Zombo', 'northern'),
(87, 'Buhweju', 'western'),
(88, 'Buliisa', 'western'),
(89, 'Bundibugyo', 'western'),
(90, 'Bushenyi', 'western'),
(91, 'Hoima', 'western'),
(92, 'Ibanda', 'western'),
(93, 'Isingiro', 'western'),
(94, 'Kabale', 'western'),
(95, 'Kabarole', 'western'),
(96, 'Kamwenge', 'western'),
(97, 'Kanungu', 'western'),
(98, 'Kasese', 'western'),
(99, 'Kibaale', 'western'),
(100, 'Kiruhura', 'western'),
(101, 'Kiryandongo', 'western'),
(102, 'Kisoro', 'western'),
(103, 'Kyegegwa', 'western'),
(104, 'Kyenjojo', 'western'),
(105, 'Masindi', 'western'),
(106, 'Mbarara', 'western'),
(107, 'Mitooma', 'western'),
(108, 'Ntoroko', 'western'),
(109, 'Ntungamo', 'western'),
(110, 'Rubirizi', 'western'),
(111, 'Rukungiri', 'western'),
(112, 'Sheema', 'western');




--
-- Table structure for table 'country'
--

CREATE TABLE IF NOT EXISTS country (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  region varchar(100) NOT NULL,
  display_order int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=234 ;

--
-- Dumping data for table 'country'
--

INSERT INTO country (id, name, region, display_order) VALUES
(1, 'Afghanistan', 'Asia', 0),
(2, 'Albania', 'Europe', 0),
(3, 'Algeria', 'Africa', 0),
(4, 'American Samoa', 'Australasia', 0),
(5, 'Andorra', 'Europe', 0),
(6, 'Angola', 'Africa', 0),
(7, 'Anguilla', 'Caribbean', 0),
(8, 'Antigua and Barbuda', 'Caribbean', 0),
(9, 'Argentina', 'South America', 0),
(10, 'Armenia', 'Europe', 0),
(11, 'Aruba', 'Caribbean', 0),
(12, 'Australia', 'Australasia', 0),
(13, 'Austria', 'Europe', 0),
(14, 'Azerbaijan', 'Europe', 0),
(15, 'Bahamas', 'Caribbean', 0),
(16, 'Bahrain', 'Middle East', 0),
(17, 'Bangladesh', 'Asia', 0),
(18, 'Barbados', 'Caribbean', 0),
(19, 'Belarus', 'Europe', 0),
(20, 'Belgium', 'Europe', 0),
(21, 'Belize', 'North America', 0),
(22, 'Benin', 'Africa', 0),
(23, 'Bermuda', 'Caribbean', 0),
(24, 'Bhutan', 'Asia', 0),
(25, 'Bolivia', 'South America', 0),
(26, 'Bosnia-Herzegovina', 'Europe', 0),
(27, 'Botswana', 'Africa', 0),
(28, 'Bouvet Island', 'Africa', 0),
(29, 'Brazil', 'South America', 0),
(30, 'Brunei', 'Asia', 0),
(31, 'Bulgaria', 'Europe', 0),
(32, 'Burkina Faso', 'Africa', 0),
(33, 'Burundi', 'Africa', 0),
(34, 'Cambodia', 'Asia', 0),
(35, 'Cameroon', 'Africa', 0),
(36, 'Canada', 'North America', 0),
(37, 'Cape Verde', 'Africa', 0),
(38, 'Cayman Islands', 'Caribbean', 0),
(39, 'Central African Republic', 'Africa', 0),
(40, 'Chad', 'Africa', 0),
(41, 'Chile', 'South America', 0),
(42, 'China', 'Asia', 0),
(43, 'Christmas Island', 'Australasia', 0),
(44, 'Cocos (Keeling) Islands', 'Australasia', 0),
(45, 'Colombia', 'South America', 0),
(46, 'Comoros', 'Africa', 0),
(47, 'Congo, Democratic Republic of the (Zaire)', 'Africa', 1),
(48, 'Congo, Republic of', 'Africa', 0),
(49, 'Cook Islands', 'Australasia', 0),
(50, 'Costa Rica', 'North America', 0),
(51, 'Croatia', 'Europe', 0),
(52, 'Cuba', 'Caribbean', 0),
(53, 'Cyprus', 'Europe', 0),
(54, 'Czech Republic', 'Europe', 0),
(55, 'Denmark', 'Europe', 0),
(56, 'Djibouti', 'Africa', 0),
(57, 'Dominica', 'Caribbean', 0),
(58, 'Dominican Republic', 'Caribbean', 0),
(59, 'Ecuador', 'South America', 0),
(60, 'Egypt', 'Africa', 0),
(61, 'El Salvador', 'North America', 0),
(62, 'Equatorial Guinea', 'Africa', 0),
(63, 'Eritrea', 'Africa', 0),
(64, 'Estonia', 'Europe', 0),
(65, 'Ethiopia', 'Africa', 0),
(66, 'Falkland Islands', 'South America', 0),
(67, 'Faroe Islands', 'Europe', 0),
(68, 'Fiji', 'Australasia', 0),
(69, 'Finland', 'Europe', 0),
(70, 'France', 'Europe', 0),
(71, 'French Guiana', 'South America', 0),
(72, 'Gabon', 'Africa', 0),
(73, 'Gambia', 'Africa', 0),
(74, 'Georgia', 'Europe', 0),
(75, 'Germany', 'Europe', 0),
(76, 'Ghana', 'Africa', 0),
(77, 'Gibraltar', 'Europe', 0),
(78, 'Greece', 'Europe', 0),
(79, 'Greenland', 'Europe', 0),
(80, 'Grenada', 'Caribbean', 0),
(81, 'Guadeloupe (French)', 'Caribbean', 0),
(82, 'Guam (USA)', 'Australasia', 0),
(83, 'Guatemala', 'North America', 0),
(84, 'Guinea', 'Africa', 0),
(85, 'Guinea Bissau', 'Africa', 0),
(86, 'Guyana', 'South America', 0),
(87, 'Haiti', 'Caribbean', 0),
(88, 'Holy See', 'Europe', 0),
(89, 'Honduras', 'North America', 0),
(90, 'Hong Kong', 'Asia', 0),
(91, 'Hungary', 'Europe', 0),
(92, 'Iceland', 'Europe', 0),
(93, 'India', 'Asia', 0),
(94, 'Indonesia', 'Asia', 0),
(95, 'Iran', 'Middle East', 0),
(96, 'Iraq', 'Middle East', 0),
(97, 'Ireland', 'Europe', 0),
(98, 'Israel', 'Middle East', 0),
(99, 'Italy', 'Europe', 0),
(100, 'Ivory Coast (Cote D`Ivoire)', 'Africa', 0),
(101, 'Jamaica', 'Caribbean', 0),
(102, 'Japan', 'Asia', 0),
(103, 'Jordan', 'Middle East', 0),
(104, 'Kazakhstan', 'Asia', 0),
(105, 'Kenya', 'Africa', 2),
(106, 'Kiribati', 'Australasia', 0),
(107, 'Kuwait', 'Middle East', 0),
(108, 'Kyrgyzstan', 'Asia', 0),
(109, 'Laos', 'Asia', 0),
(110, 'Latvia', 'Europe', 0),
(111, 'Lebanon', 'Middle East', 0),
(112, 'Lesotho', 'Africa', 0),
(113, 'Liberia', 'Africa', 0),
(114, 'Libya', 'Africa', 0),
(115, 'Liechtenstein', 'Europe', 0),
(116, 'Lithuania', 'Europe', 0),
(117, 'Luxembourg', 'Europe', 0),
(118, 'Macau', 'Asia', 0),
(119, 'Macedonia', 'Europe', 0),
(120, 'Madagascar', 'Africa', 0),
(121, 'Malawi', 'Africa', 0),
(122, 'Malaysia', 'Asia', 0),
(123, 'Maldives', 'Asia', 0),
(124, 'Mali', 'Africa', 0),
(125, 'Malta', 'Europe', 0),
(126, 'Marshall Islands', 'Australasia', 0),
(127, 'Martinique (French)', 'Caribbean', 0),
(128, 'Mauritania', 'Africa', 0),
(129, 'Mauritius', 'Africa', 0),
(130, 'Mayotte', 'Africa', 0),
(131, 'Mexico', 'North America', 0),
(132, 'Micronesia', 'Australasia', 0),
(133, 'Moldova', 'Europe', 0),
(134, 'Monaco', 'Europe', 0),
(135, 'Mongolia', 'Asia', 0),
(136, 'Montenegro', 'Europe', 0),
(137, 'Montserrat', 'Caribbean', 0),
(138, 'Morocco', 'Africa', 0),
(139, 'Mozambique', 'Africa', 0),
(140, 'Myanmar', 'Asia', 0),
(141, 'Namibia', 'Africa', 0),
(142, 'Nauru', 'Australasia', 0),
(143, 'Nepal', 'Asia', 0),
(144, 'Netherlands', 'Europe', 0),
(145, 'Netherlands Antilles', 'Caribbean', 0),
(146, 'New Caledonia (French)', 'Australasia', 0),
(147, 'New Zealand', 'Australasia', 0),
(148, 'Nicaragua', 'North America', 0),
(149, 'Niger', 'Africa', 0),
(150, 'Nigeria', 'Africa', 0),
(151, 'Niue', 'Australasia', 0),
(152, 'Norfolk Island', 'Australasia', 0),
(153, 'North Korea', 'Asia', 0),
(154, 'Northern Mariana Islands', 'Asia', 0),
(155, 'Norway', 'Europe', 0),
(156, 'Oman', 'Middle East', 0),
(157, 'Pakistan', 'Asia', 0),
(158, 'Palau', 'Australasia', 0),
(159, 'Panama', 'North America', 0),
(160, 'Papua New Guinea', 'Australasia', 0),
(161, 'Paraguay', 'South America', 0),
(162, 'Peru', 'South America', 0),
(163, 'Philippines', 'Asia', 0),
(164, 'Pitcairn Island', 'Australasia', 0),
(165, 'Poland', 'Europe', 0),
(166, 'Polynesia (French)', 'Australasia', 0),
(167, 'Portugal', 'Europe', 0),
(168, 'Puerto Rico', 'Caribbean', 0),
(169, 'Qatar', 'Middle East', 0),
(170, 'Reunion', 'Africa', 0),
(171, 'Romania', 'Europe', 0),
(172, 'Russia', 'Europe', 0),
(173, 'Rwanda', 'Africa', 2),
(174, 'Saint Helena', 'Africa', 0),
(175, 'Saint Kitts and Nevis', 'Caribbean', 0),
(176, 'Saint Lucia', 'Caribbean', 0),
(177, 'Saint Pierre and Miquelon', 'North America', 0),
(178, 'Saint Vincent and Grenadines', 'Caribbean', 0),
(179, 'Samoa', 'Australasia', 0),
(180, 'San Marino', 'Europe', 0),
(181, 'Sao Tome and Principe', 'Africa', 0),
(182, 'Saudi Arabia', 'Middle East', 0),
(183, 'Senegal', 'Africa', 0),
(184, 'Serbia', 'Europe', 0),
(185, 'Seychelles', 'Africa', 0),
(186, 'Sierra Leone', 'Africa', 0),
(187, 'Singapore', 'Asia', 0),
(188, 'Slovakia', 'Europe', 0),
(189, 'Slovenia', 'Europe', 0),
(190, 'Solomon Islands', 'Australasia', 0),
(191, 'Somalia', 'Africa', 0),
(192, 'South Africa', 'Africa', 0),
(193, 'South Georgia and South Sandwich Islands', 'South America', 0),
(194, 'South Korea', 'Asia', 0),
(195, 'South Sudan', 'Africa', 0),
(196, 'Spain', 'Europe', 0),
(197, 'Sri Lanka', 'Asia', 0),
(198, 'Sudan', 'Africa', 1),
(199, 'Suriname', 'South America', 0),
(200, 'Svalbard and Jan Mayen Islands', 'Europe', 0),
(201, 'Swaziland', 'Africa', 0),
(202, 'Sweden', 'Europe', 0),
(203, 'Switzerland', 'Europe', 0),
(204, 'Syria', 'Middle East', 0),
(205, 'Taiwan', 'Asia', 0),
(206, 'Tajikistan', 'Asia', 0),
(207, 'Tanzania', 'Africa', 2),
(208, 'Thailand', 'Asia', 0),
(209, 'Timor-Leste (East Timor)', 'Australasia', 0),
(210, 'Togo', 'Africa', 0),
(211, 'Tokelau', 'Australasia', 0),
(212, 'Tonga', 'Australasia', 0),
(213, 'Trinidad and Tobago', 'Caribbean', 0),
(214, 'Tunisia', 'Africa', 0),
(215, 'Turkey', 'Middle East', 0),
(216, 'Turkmenistan', 'Asia', 0),
(217, 'Turks and Caicos Islands', 'Caribbean', 0),
(218, 'Tuvalu', 'Australasia', 0),
(219, 'Uganda', 'Africa', 5),
(220, 'Ukraine', 'Europe', 0),
(221, 'United Arab Emirates', 'Middle East', 0),
(222, 'United Kingdom', 'Europe', 0),
(223, 'United States', 'North America', 0),
(224, 'Uruguay', 'South America', 0),
(225, 'Uzbekistan', 'Asia', 0),
(226, 'Vanuatu', 'Australasia', 0),
(227, 'Venezuela', 'South America', 0),
(228, 'Vietnam', 'Asia', 0),
(229, 'Virgin Islands', 'Caribbean', 0),
(230, 'Wallis and Futuna Islands', 'Australasia', 0),
(231, 'Yemen', 'Middle East', 0),
(232, 'Zambia', 'Africa', 0),
(233, 'Zimbabwe', 'Africa', 0);



ALTER TABLE `address` ADD `importance` VARCHAR( 100 ) NOT NULL AFTER `address_type` ;
ALTER TABLE `address` CHANGE `sub_county_id` `county` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL ;
ALTER TABLE `address` DROP `region_id` ;
ALTER TABLE `address` CHANGE `zipcode` `zipcode` VARCHAR( 10 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL ;



ALTER TABLE `message` ADD `copy_admin` ENUM( 'Y', 'N' ) NOT NULL DEFAULT 'Y' AFTER `details` ;
ALTER TABLE `message` ADD `subject` VARCHAR( 300 ) NOT NULL AFTER `message_type` ;

INSERT INTO message (id, message_type, subject, details, copy_admin, date_added, added_by, last_updated, last_updated_by) VALUES
(1, 'new_teacher_first_step', 'Your Verification Code for TMIS', 'Hi _FIRST_NAME_,\r\n<br>\r\n<br>A profile has been created for you at the Teacher Management Information System (TMIS). You will need this code to confirm your account:\r\n<br>_VERIFICATION_CODE_\r\n<br>\r\n<br>In case you closed the TMIS website, go to the link below to continue with your registration:\r\n<br>_LOGIN_LINK_\r\n<br>You will need the following details to login:\r\n<br>\r\nYour user name: _EMAILADDRESS_\r\n<br>Your Temporary Password: _PASSWORD_\r\n<br>\r\n<br>Regards,\r\n<br>Your TMIS Admin Team\r\n<br>', 'Y', '2015-01-14 00:00:00', '1', '0000-00-00 00:00:00', '');



ALTER TABLE `person` ADD `citizenship_id` VARCHAR( 100 ) NOT NULL AFTER `date_of_birth` ,
ADD `citizenship_type` VARCHAR( 100 ) NOT NULL AFTER `citizenship_id` ;



DROP TABLE IF EXISTS `query`;
CREATE TABLE `query` (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  `code` varchar(300) NOT NULL,
  details text NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;

INSERT INTO query (id, code, details) VALUES
(1, 'get_list_of_districts', 'SELECT *, name AS value, name AS display FROM district ORDER BY name'),
(2, 'get_list_of_countries', 'SELECT *, name AS value, name AS display FROM country ORDER BY display_order DESC, name ASC'),
(3, 'add_person_data', 'INSERT INTO person (first_name, last_name, gender, date_of_birth, date_added) VALUES (''_FIRST_NAME_'', ''_LAST_NAME_'', ''_GENDER_'', ''_DATE_OF_BIRTH_'', NOW())'),
(4, 'add_contact_data', 'INSERT INTO contact (contact_type, carrier_id, details, parent_id, parent_type, date_added) VALUES (''_CONTACT_TYPE_'', ''_CARRIER_ID_'', ''_DETAILS_'', ''_PARENT_ID_'', ''_PARENT_TYPE_'', NOW())'),
(5, 'add_new_address', 'INSERT INTO address (parent_id, parent_type, address_type, importance, details, county, district_id, country_id, date_added)\r\n\r\n(SELECT ''_PARENT_ID_'' AS parent_id, \r\n''_PARENT_TYPE_'' AS parent_type, \r\n''_ADDRESS_TYPE_'' AS address_type, \r\n''_IMPORTANCE_'' AS importance, \r\n''_DETAILS_'' AS details, \r\n ''_COUNTY_'' AS county,\r\nIF((SELECT id FROM district WHERE name=''_DISTRICT_'' LIMIT 1) IS NOT NULL, (SELECT id FROM district WHERE name=''_DISTRICT_'' LIMIT 1), ''_DISTRICT_'') AS district_id, \r\nIF((SELECT id FROM country WHERE name=''_COUNTRY_'' LIMIT 1) IS NOT NULL, (SELECT id FROM country WHERE name=''_COUNTRY_'' LIMIT 1), ''_COUNTRY_'') AS country_id,\r\nNOW() AS date_added\r\n)'),
(6, 'add_user_data', 'INSERT INTO user (person_id, 	login_name, login_password, date_added) VALUES (''_PERSON_ID_'', ''_LOGIN_NAME_'', ''_LOGIN_PASSWORD_'', NOW())'),
(7, 'get_message_template', 'SELECT * FROM message WHERE message_type=''_MESSAGE_TYPE_'''),
(8, 'add_event_log', 'INSERT INTO log (log_code, result, details, date_added) VALUES (''_LOG_CODE_'', ''_RESULT_'', ''_DETAILS_'', NOW())'),
(9, 'update_person_profile', 'UPDATE person SET _QUERY_PART_ WHERE person_id=''_PERSON_ID_'''),
(10, 'update_person_citizenship', 'UPDATE person P LEFT JOIN country C ON (C.name=''_CITIZEN_COUNTRY_'') \r\nSET P.citizenship_id=C.id, P.citizenship_type=''_CITIZENSHIP_TYPE_'' WHERE P.id=''_PERSON_ID_''');



